[default.general]
chip = "nrf52833_xxAA"

[default.reset]
halt_afterwards = false

[default.rtt]
enabled = true
channels = [{ up = 0, name = "defmt_rtt", format = "Defmt" }]

[default.gdb]
enabled = false
