[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "probe-run --chip nRF52833_xxAA"
rustflags = [
  "-C", "linker=flip-link",
  "-C", "link-arg=-Tlink.x",
  "-C", "link-arg=-Tdefmt.x",
  # This is needed if your flash or ram addresses are not aligned to 0x10000 in memory.x
  # See https://github.com/rust-embedded/cortex-m-quickstart/pull/95
  "-C", "link-arg=--nmagic",
]

[build]
# target 通过 alias 指定，不设置全局 target 以避免影响 cargo test 和 rust-analyzer
# 编译用 cargo b，烧录用 cargo rb

[alias]
rb = "run --bin musicbox --target thumbv7em-none-eabihf"
b = "build --target thumbv7em-none-eabihf"